//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seafplus.BusinessLogic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public Card()
        {
            this.Checklists = new HashSet<Checklist>();
            this.UserCards = new HashSet<UserCard>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public int ListId { get; set; }
        public int OrderNumber { get; set; }
    
        public virtual List List { get; set; }
        public virtual ICollection<Checklist> Checklists { get; set; }
        public virtual ICollection<UserCard> UserCards { get; set; }
    }
}
