//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seafplus.BusinessLogic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class List
    {
        public List()
        {
            this.Cards = new HashSet<Card>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int BoardId { get; set; }
        public int OrderNumber { get; set; }
    
        public virtual Board Board { get; set; }
        public virtual ICollection<Card> Cards { get; set; }
    }
}
