//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seafplus.BusinessLogic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.Boards = new HashSet<Board>();
            this.UserOrganizations = new HashSet<UserOrganization>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsPrivate { get; set; }
    
        public virtual ICollection<Board> Boards { get; set; }
        public virtual ICollection<UserOrganization> UserOrganizations { get; set; }
    }
}
