//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seafplus.BusinessLogic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserBoards = new HashSet<UserBoard>();
            this.UserCards = new HashSet<UserCard>();
            this.UserOrganizations = new HashSet<UserOrganization>();
        }
    
        public int Id { get; set; }
        public Nullable<long> GoogleId { get; set; }
        public int UserRoleId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<UserBoard> UserBoards { get; set; }
        public virtual ICollection<UserCard> UserCards { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual ICollection<UserOrganization> UserOrganizations { get; set; }
    }
}
